### ISSUE TITLE
removal from CRAN

### ISSUE THREAD

**Issue by dankelley** [tgouhier/biwavelet#79]
I was just going into CRAN to get an email address to report an issue (which I'll do in a moment, separately) but I see that `biwavelet` has been removed from CRAN.

Q1: is there a plan to get biwavelet back on CRAN?

Q2: do you recommend a replacement, if not?

**Comment by tgouhier** [comment]
The package was pulled from CRAN because of a minor issue with the inclusion of microbenchmarks. Unfortunately, both @vsimko and I are swamped right now and thus do not have time to fix the issue and push an update to CRAN. It is still possible to download and install biwavelet from GitHub via the devtools package. As for alternatives, the WaveletComp package seems to replicate much of the functionality of biwavelet, so I'd recommend that.

**Comment by dankelley** [comment]
Thanks for the update!

**Comment by tgouhier** [comment]
Hi @dankelley,

I fixed the CRAN-related issues and version 0.20.17 of biwavelet should be back on CRAN shortly.

Thanks!

**Comment by dankelley** [comment]
Great to hear. Thanks!!
